// API

const projects = [
  {
    id: '14',
    title: 'myfirstwebsite1.0.8',
    projectName: 'Cacteria',
    projectImg: './website-img/myfirstwebsite1.0.8.png',
    desc: 'I created this website after I learned about serverless function. I create my own API using netlify and airtable.Cacteria is a ecommerce that sell cactus. ',
    gitHub: 'https://github.com/maxrpark/cacteria',
    site: 'https://cacteria.netlify.app/',
  },
  {
    id: '13',
    title: 'myfirstwebsite 1.0.7',
    projectName: 'The Movie Masters',
    projectImg: './website-img/myfirstwebsite1.0.7.jpg',
    desc: 'The Movie Masters is a website where the movie critics meet. Here you can find all your favorite movies, read reviews, create a profile and add your favorites movies to your list. This website uses the TMDB API. ',
    gitHub: 'https://github.com/maxrpark/myfirstwebsite1.0.7',
    site: 'https://themoviemasters.netlify.app/',
  },
  {
    id: '12',
    title: 'Wordpress 3',
    projectName: 'Vegetariano en Corea',
    projectImg: './website-img/wordpress-3.jpg',
    desc: 'This website was built using OCEAN WP, it is my personal blog, where I share information, tips and reviews for vegetarian people living in South Korea. It has links to the YouTube channel and Instagram profile of the same project. ',
    gitHub: '',
    site: 'https://vegetarianoencorea.com/',
  },
  {
    id: '11',
    title: 'Wordpress 2',
    projectName: 'All About Mendoza',
    projectImg: './website-img/wordpress-2.jpg',
    desc: 'This wordlpress website is build using DIVI, is a Travel Guide Website about Mendoza, Argentina. The main idea was to provide valuable info but also to create a niche website. It has google ads and affiliate links.',
    gitHub: '',
    site: 'https://allaboutmendoza.com/',
  },
  {
    id: '10',
    title: 'Wordpress 1',
    projectName: 'Aprende Coreano Paso a Paso',
    projectImg: './website-img/wordpress-1.jpg',
    desc: 'This is the first website I built with wordpress, it is a LMS website to learn Korean language. It has courses, shop, blog. It currently has nearly 100k views per month and most of the articles rank in the first page of google. ',
    gitHub: '',
    site: 'https://aprendecoreanopasoapaso.com/',
  },
  {
    id: '9',
    title: 'myfirstwebsite 1.0.6',
    projectName: 'Baby Names Website',
    projectImg: './website-img/myfirstwebsite1.0.6.jpg',
    desc: 'A website that will help you decide the name of your baby. It can provide a list with the top 50 names for girls and boys.<br> It can also help you decide between your favorites names. The site was a shop section and A&Q section. ',
    gitHub: 'https://github.com/maxrpark/myfirstwebsite1.0.6',
    site: 'https://myfirstwebsite1-0-6.netlify.app/',
  },
  {
    id: '8',
    title: 'myfirstwebsite 1.0.5',
    projectName: 'Covid Report',
    projectImg: './website-img/myfirstwebsite1.0.5.jpg',
    desc: 'This website show updated Argentina COVID 19 report.  <br> This is my first website getting information form and external API',
    gitHub: 'https://github.com/maxrpark/myfirstwebsite1.0.5',
    site: 'https://myfirstwebsite1-0-5.netlify.app/',
  },
  {
    id: '7',
    title: 'myfirstwebsite 1.0.4',
    projectName: 'My Projects',
    projectImg: './website-img/myfirstwebsite1.0.4.jpg',
    desc: 'The main idea of this project it was to have a place where I could show all my other project too. I guess the best thing about this project is the DARK MODE. Try it out!',
    gitHub: 'https://github.com/maxrpark/myfirstwebsite1.0.4',
    site: 'https://myfirstwebsite1-0-4.netlify.app/',
  },
  {
    id: '6',
    title: 'myfirstwebsite 1.0.3',
    projectName: 'My twitter account',
    projectImg: './website-img/myfirstwebsite1.0.3.jpg',
    desc: 'When I started  this website I did not knot this was going to be the most challenging project I ever did. It more a less combine everything I have been learning so far.',
    gitHub: 'https://github.com/maxrpark/maxrpark-myfirstwebsite1.0.3',
    site: 'https://myfirstwebsite1-0-3.netlify.app/',
  },
  {
    id: '5',
    title: 'myfirstwebsite 1.0.2',
    projectName: 'Mind Reader',
    projectImg: './website-img/myfirstwebsite1.0.2.jpg',
    desc: 'This is a simple website that I create to practice more JavaScript. It is small game that I always liked since I was a child. The main thing I got to practices with this website was forEach method.',
    gitHub: 'https://github.com/maxrpark/maxrpark-myfirstwebsite1.0.2',
    site: 'https://myfirstwebsite1-0-2.netlify.app/',
  },
  {
    id: '4',
    title: 'myfirstwebsite 1.0',
    projectName: 'Vegan Ramen',
    projectImg: './website-img/myfirstwebsite1.0.jpg',
    desc: 'My Vegan Ramen is the first website I created after started learning JavaScript. Of course at the time I created it, it was my biggest project but not only because I was adding JavaScript to my project but because this website is a multi-language website.',
    gitHub: 'https://github.com/maxrpark/myFirstWebsite1-0',
    site: 'https://myfirstwebsite1-0.netlify.app/',
  },
  {
    id: '3',
    title: 'myfirstwebsite 0.3',
    projectName: 'My first Website 0.3',
    projectImg: './website-img/myfirstwebsite0.3.jpg',
    desc: 'In this website I tried to create different landing pages for different purpose, in this project contains four landing pages which are Restaurant, Contact, Newsletter and Product. This website is pure HTML and CSS.',
    gitHub: 'https://github.com/maxrpark/myFirstWebsite0.3',
    site: 'https://myfirstwebsite0-3.netlify.app/',
  },
  {
    id: '2',
    title: 'myfirstwebsite 0.2',
    projectName: 'My first Website 0.2',
    projectImg: './website-img/myfirstwebsite0.2.jpg',
    desc: 'I create this website after I learned about CSS Grid and Flexbox. I just wanted to practice what I learned I try to create the same design using CSS Grid and Flexbox. This website also has a small code JavaScript I took from google',

    gitHub: 'https://github.com/maxrpark/myFirstWebsite0.2',
    site: 'https://myfirstwebsite0-2.netlify.app/',
  },
  {
    id: '1',
    title: 'myfirstwebsite 0.1',
    projectName: 'My first Website 0.1',
    projectImg: './website-img/myfirstwebsite0.1.jpg',
    desc: 'This was my first HTML and CSS website. It is a simply website that will always make me proud, because at that time I practically knew nothing about HTML and CSS but still I managed to create this website.',
    gitHub: 'https://github.com/maxrpark/myfirstwebsiteo.1',
    site: 'https://myfirstwebsite0-1.netlify.app/',
  },
];

export default projects;
